name 'tekenny-splunk'
version '0.1.0'

author 'dhogland, modifieing authors: Will Ferrer and Ethan Brooks (Run the Business): Thomas Kenny (tekenny)'
license 'Apache License, Version 2.0'
project_page 'https://github.com/tekenny/puppet-splunk'
source ''
summary 'This class installs and configurs splunk. It is a paramaritized version of dhogland/splunk (https://github.com/dhogland/splunk) and includes some small bug fixes, default values added and other tweaks.
'
description 'splunk

This class installs and configurs splunk. It is a paramaritized version of dhogland/splunk (https://github.com/dhogland/splunk) and includes some small bug fixes, default values added and other tweaks.


Examples:

	class{"splunk":
	  logging_server      => \'<logging server>\',
	}

Changes from dhogland/splunk
-------

- Made splunk class paramaritized so it can work with out the entriprise console
- Added support for amd64 systems
- Fixed variable name "installer" in windows set ups to reference: ${splunk::params::installer} (untested by probably fixed issues with windows installs)
- Add the installerfilespath option. This allows you to store your installer files in a seperate module or else where on the disk.

Changes from runthebusiness/splunk
-------
- Added parameter ${splunk::user} to set user and ${splunk::group} to set group on managed files (Linux only). Default is splunk
- Added parameter ${splunk::provider} to set be able to set provider as yum so package can be installed via YUM rather than placing package in module\'s files directory (Linux only). Default is to install from the module\'s files directory.
- Added parameter ${splunk::host} which is the host setting for inputs.conf (Linux only). Default is $decideOnStartup
- Added a dependency on the puppetlabs/concat forge module.
- Refactored splunk::monitor and how inputs.conf is managed to support defining a blacklist and/or whitelist
- Added parameter ${splunk::defaultGroup} which is the defaultGroup setting for outputs.conf (Linux only). Default is default-autolb-group
- Changed default for splunk_ver to 5.0.3-163460
- Added custom fact splunksslkeysfilepassword this is obtained and used in the template for server.conf and is generated when splunk is started if it doesn\'t already exist.
- Added management of server.conf
- Added management of limits.conf and added parameter splunk::maxKBps

Author
-------
dhogland

Modifieing Authors
-------
Will Ferrer, Ethan Brooks

Contributing Authors  
-------
Brendan Murtagh

Licensees
-------
2012 developed under license for Switchsoft LLC http://www.switchsoft.com a "Direct response telephony company" as part of it\'s "VOIP Call distribution, ROI analysis platform, call recording, and IVR for inbound and outbound sales" and Run the Business Systems LLC a "Technology development investment group" as part of it\'s "PHP, Javascript rapid application development framework and MySQL analysis tools"

License
-------
Licensed under the terms of the Apache License, Version 2.0


Contact
-------
thomas.e.kenny@gmail.com

Support
-------

Please send tickets and issues to our contact email address or at: https://github.com/tekenny/puppet-splunk/issues

Project Url
-------
https://github.com/tekenny/puppet-splunk

'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'puppetlabs/firewall', '>=0.0.4'
